version: '3'

services:
  testserver:
    image: testserver
    ports:
     - "8080:8080"
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  scorpio:
    image: scorpiobroker/all-in-one-runner:ubuntu-latest
    environment:
      DBHOST: postgres
    ports:
      - "9090:9090"
    depends_on:
      - postgres
